# Generated by Django 6.0.5 on 2026-06-11 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caseta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('costo', models.FloatField(default=0.0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_combustible', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], default='gasolina', max_length=20)),
                ('rendimiento_kmL', models.FloatField(default=12.0)),
                ('tanque_litros', models.FloatField(default=40.0)),
                ('nivel_combustible', models.FloatField(default=100.0)),
                ('velocidad_promedio', models.FloatField(default=60.0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaTrafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('latitud_centro', models.FloatField()),
                ('longitud_centro', models.FloatField()),
                ('radio_km', models.FloatField(default=0.5)),
                ('nivel_trafico', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='medio', max_length=10)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='rutaplaneada',
            old_name='costo_km',
            new_name='combustible_L',
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='distancia_segmento_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='tiempo_segmento_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoruta',
            name='tipo',
            field=models.CharField(choices=[('origen', 'Origen'), ('intermedio', 'Intermedio'), ('destino', 'Destino'), ('caseta', 'Caseta'), ('trafico', 'Zona de tráfico')], default='intermedio', max_length=15),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='costo_casetas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='costo_gasolina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='distancia_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='es_alterna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='ruta_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternas', to='gps.rutaplaneada'),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='tiempo_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='rutaplaneada',
            name='algoritmo',
            field=models.CharField(choices=[('astar', 'A* Manhattan'), ('costo_uniforme', 'Costo Uniforme (UCS)'), ('genetico', 'Genético Evolutivo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rutaplaneada',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='rutaplaneada',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas', to='gps.vehiculo'),
        ),
    ]
