# Generated by Django 6.0.5 on 2026-06-21 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_caseta_vehiculo_zonatrafico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rutaplaneada',
            name='vehiculo',
        ),
        migrations.AlterModelOptions(
            name='caseta',
            options={'verbose_name': 'Caseta', 'verbose_name_plural': 'Casetas'},
        ),
        migrations.AlterModelOptions(
            name='zonatrafico',
            options={'verbose_name': 'Zona de tráfico', 'verbose_name_plural': 'Zonas de tráfico'},
        ),
        migrations.RenameField(
            model_name='rutaplaneada',
            old_name='combustible_L',
            new_name='costo_km',
        ),
        migrations.RenameField(
            model_name='zonatrafico',
            old_name='latitud_centro',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='zonatrafico',
            old_name='longitud_centro',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='zonatrafico',
            old_name='nivel_trafico',
            new_name='nivel',
        ),
        migrations.RemoveField(
            model_name='puntoruta',
            name='distancia_segmento_km',
        ),
        migrations.RemoveField(
            model_name='puntoruta',
            name='tiempo_segmento_min',
        ),
        migrations.RemoveField(
            model_name='puntoruta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='rutaplaneada',
            name='costo_casetas',
        ),
        migrations.RemoveField(
            model_name='rutaplaneada',
            name='costo_gasolina',
        ),
        migrations.RemoveField(
            model_name='rutaplaneada',
            name='distancia_km',
        ),
        migrations.RemoveField(
            model_name='rutaplaneada',
            name='es_alterna',
        ),
        migrations.RemoveField(
            model_name='rutaplaneada',
            name='ruta_principal',
        ),
        migrations.AddField(
            model_name='caseta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zonatrafico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caseta',
            name='costo',
            field=models.FloatField(help_text='Costo en MXN'),
        ),
        migrations.AlterField(
            model_name='caseta',
            name='nombre',
            field=models.CharField(default='Caseta', max_length=100),
        ),
        migrations.AlterField(
            model_name='puntoruta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rutaplaneada',
            name='algoritmo',
            field=models.CharField(default='astar_manhattan', max_length=50),
        ),
        migrations.AlterField(
            model_name='rutaplaneada',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zonatrafico',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Vacío = aplica todo el día', null=True),
        ),
        migrations.AlterField(
            model_name='zonatrafico',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Vacío = aplica todo el día', null=True),
        ),
        migrations.AlterField(
            model_name='zonatrafico',
            name='nombre',
            field=models.CharField(default='Zona de tráfico', max_length=100),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
