# Generated by Django 6.0.5 on 2026-06-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_remove_rutaplaneada_vehiculo_alter_caseta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordenada',
            name='gasolina',
            field=models.FloatField(blank=True, help_text='Nivel de gasolina en porcentaje (0-100%)', null=True),
        ),
    ]
