# Generated by Django 6.0.5 on 2026-06-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_coordenada_gasolina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='gasolina',
            field=models.FloatField(blank=True, help_text='Nivel de gasolina 0-100%', null=True),
        ),
    ]
